# Generated by Django 4.0.4 on 2025-04-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhtom_registration', '0002_alter_latexuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='latexuser',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
